---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"

    target-branch: "dev"

    labels:
      - "dependencies"

    assignees:
      - "Argmaster"

    reviewers:
      - "Argmaster"
