name: Language Server Bug Report Form
description: Report a bug in PyGerber's language server.
title: "[Language Server]: <when-i-am-doing-something-then-something-fails>"
labels: ["language-server", "bug", "waiting-for-checkboxes"]
projects: ["argmaster/3"]
assignees:
  - Argmaster
body:
  - type: markdown
    attributes:
      value: |
        # Language Server Bug Report

        Thank you for reporting a bug in PyGerber's language server. Please fill out the
        following form to help us understand the issue better.

  - type: checkboxes
    id: pre_checks
    attributes:
      label: Mandatory checks
      description: |
        Before opening this issue I have done the following:
      options:
        - label: I have reviewed the README for language server related guidelines and haven't found a solution there.
          required: true
        - label: I have reviewed the language server documentation and haven't found a solution there.
          required: true
        - label: I have reviewed the existing open issues and verified that this is not a duplicate.
          required: true
        - label: I have reviewed the existing closed issues and verified that this was already resolved or marked as won't fix.
          required: true
        - label: I have reviewed the existing pull requests and verified that this is not a already known issue.
          required: true
        - label: I have reviewed the existing discussions and verified that this is not a already known issue.
          required: true

  - type: markdown
    attributes:
      value: >
        If you have found a issue / discussion / pull request describing similar but not quite
        matching issue, You can still open new issue, we will review it and decide if we want to
        merge them.

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: >
        Steps to reproduce the behavior.

        You can include code snippets or screenshots for individual steps to make it easier to
        reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error

  - type: textarea
    attributes:
      label: Expected behavior
      description: >
        A clear and concise description of what you expected to happen. If this issue is related
        to image rendering, please post a screenshot from
        [Reference Gerber Viewer](https://gerber-viewer.ucamco.com/) or CAD software used. If
        the design is confidential, follow guidelines regarding confidential files available in
        `Additional context` section below.
      placeholder: |
        The image should look like this...
        Description of the element should be more like this...
        In the specification it is mentioned that...

  - type: textarea
    attributes:
      label: Additional context
      description: >
        If applicable, add screenshots, code examples, or any other resources that can speed up
        process of reproducing and fixing the issue.


        If your issue was discovered with use of specific source file (e.g. in Gerber format),
        please attach it to the issue. If file is confidential, please create minimal subset of
        the file which can be shared in public and allows to reproduce the issue.


        If you are not able to create minimal reproduction for confidential source, you can
        email me the confidential file at `argmaster.world@gmail.com` with the issue title in
        the subject. I will not share the file anywhere in public and will delete it after the
        issue is resolved. We can discuss NDA agreements via email if needed.


        You still should create a public issue based on this template for the issue to be
        investigated, please use `<confidential-file>`, `<confidential-image>`, etc. as a
        placeholders for the confidential files.

      placeholder: |
        ...

  - type: markdown
    attributes:
      value: >
        ### Environment

  - type: input
    id: os_name
    attributes:
      label: Operating system
      placeholder: Windows 10, Ubuntu 20.04, macOS 11.0, etc.

  - type: input
    id: python_version
    attributes:
      label: Python version
      placeholder: 3.8.5, 3.9.0, etc.

  - type: input
    id: pygerber_version
    attributes:
      label: PyGerber version
      placeholder: 0.1.0, 0.2.0, etc.

  - type: input
    id: ide_name
    attributes:
      label: Integrated Development Environment (IDE)
      placeholder: Visual Studio Code, etc.

  - type: input
    id: ide_version
    attributes:
      label: IDE version
      placeholder: 1.90.0, 1.93.1, etc.

  - type: checkboxes
    id: post_checks
    attributes:
      label: Optional agreements
      description: >
        Agreements listed below are optional, but consider checking them if it is not
        harmful for you to do so. You can greatly improve PyGerber doing so.
      options:
        - label: >
            I want to include example source files attached to this issue in the
            test suite of PyGerber for regression testing purposes. I understand that
            the files will be publicly available in the repository.
          required: false
        - label: >
            I want to include separate LICENSE file for resource files attached as a
            result of an agreement described in first checkbox in this section.
          required: false
        - label: >
            I want to include separate README file for resource files attached as a
            result of an agreement described in first checkbox in this section.
          required: false
