---
name: Code Quality

on:
  push:
    branches:
      - main
      - dev
      - fix/**
      - hotfix/**
      - feature/**
      - release/**
      - dependabot/**
      - maintenance/**
      - refactor/**

  pull_request:
    branches:
      - main
      - dev
      - fix/**
      - hotfix/**
      - feature/**
      - release/**
      - dependabot/**
      - maintenance/**
    types:
      - opened
      - reopened

  schedule:
    - cron: 0 12 * * 6

  workflow_dispatch:

concurrency:
  group: ${{ github.action_path }}-${{ github.ref }}-code-quality
  cancel-in-progress: false

jobs:
  run-code-quality-checks:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.11"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.6.0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.7.0
        with:
          python-version: ${{ matrix.python-version }}
          architecture: "x64"

      - name: Install Poetry
        run: pip install poetry==1.6.1

      - name: Install dependencies
        run: poetry install --no-cache --sync

      - name: Run code quality checks with pre-commit
        run: poetry run poe run-code-quality-checks
