name: Pull request tests

on:
  pull_request:

  push:
    branches:
      - develop

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install project external dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox coverage

      - name: Check code quality
        run: |
          tox -e check

      - name: Run release tests
        run: |
          tox -e py39-release
          coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests
          fail_ci_if_error: true
          verbose: true
